"""Add role field to User model

Revision ID: 04ac06a3b47a
Revises: ac11fb10d0ee
Create Date: 2025-02-08 20:34:28.051420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04ac06a3b47a'
down_revision = 'ac11fb10d0ee'
branch_labels = None
depends_on = None

def upgrade():
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('role', sa.String(length=20), nullable=False, server_default='default')
        )
    # Optionally, remove the server_default after populating existing rows:
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role', server_default=None)



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
